export const DummyData = [
	{
		no: 1,
		surah_idn: 'Al-Fatihah',
		surah_arabic: 'الفاتحة',
		arti: 'Pembukaan',
		total_ayah: '7',
		revealed_in: 'Mekah',
	},
	{
		no: 2,
		surah_idn: 'Al-Baqarah',
		surah_arabic: 'البقرة',
		arti: 'Sapi Betina',
		total_ayah: '286',
		revealed_in: 'Madinah',
	},
	{
		no: 3,
		surah_idn: "Ali 'Imran",
		surah_arabic: 'آل عمران',
		arti: 'Keluarga Imran',
		total_ayah: '200',
		revealed_in: 'Madinah',
	},
	{
		no: 4,
		surah_idn: "An-Nisa'",
		surah_arabic: 'النساء',
		arti: 'Wanita',
		total_ayah: '176',
		revealed_in: 'Madinah',
	},
	{
		no: 5,
		surah_idn: "Al-Ma'idah",
		surah_arabic: 'المائدة',
		arti: 'Hidangan',
		total_ayah: '120',
		revealed_in: 'Madinah',
	},
	{
		no: 6,
		surah_idn: "Al-An'am",
		surah_arabic: 'الأنعام',
		arti: 'Binatang Ternak',
		total_ayah: '165',
		revealed_in: 'Mekah',
	},
	{
		no: 7,
		surah_idn: "Al-A'raf",
		surah_arabic: 'الأعراف',
		arti: 'Tempat Tertinggi',
		total_ayah: '206',
		revealed_in: 'Mekah',
	},
	{
		no: 8,
		surah_idn: 'Al-Anfal',
		surah_arabic: 'الأنفال',
		arti: 'Harta Rampasan Perang',
		total_ayah: '75',
		revealed_in: 'Madinah',
	},
	{
		no: 9,
		surah_idn: 'At-Tawbah',
		surah_arabic: 'التوبة',
		arti: 'Pengampunan',
		total_ayah: '129',
		revealed_in: 'Madinah',
	},
	{
		no: 10,
		surah_idn: 'Yunus',
		surah_arabic: 'يونس',
		arti: 'Nabi Yunus',
		total_ayah: '109',
		revealed_in: 'Mekah',
	},
	{
		no: 11,
		surah_idn: 'Hud',
		surah_arabic: 'هود',
		arti: 'Nabi Hud',
		total_ayah: '123',
		revealed_in: 'Mekah',
	},
	{
		no: 12,
		surah_idn: 'Yusuf',
		surah_arabic: 'يوسف',
		arti: 'Nabi Yusuf',
		total_ayah: '111',
		revealed_in: 'Mekah',
	},
];

export const DummyAyah = [
	{
		id: '1',
		no: 1,
		ayat: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
		latin: 'Bismillāhir-raḥmānir-raḥīm',
		arti_id: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.',
	},
	{
		id: '2',
		no: 2,
		ayat: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
		latin: 'Al-ḥamdu lillāhi rabbil-‘ālamīn',
		arti_id: 'Segala puji bagi Allah, Tuhan seluruh alam.',
	},
	{
		id: '3',
		no: 3,
		ayat: 'الرَّحْمَٰنِ الرَّحِيمِ',
		latin: 'Ar-raḥmānir-raḥīm',
		arti_id: 'Yang Maha Pengasih, Maha Penyayang.',
	},
	{
		id: '4',
		no: 4,
		ayat: 'مَالِكِ يَوْمِ الدِّينِ',
		latin: 'Māliki yaumid-dīn',
		arti_id: 'Pemilik hari pembalasan.',
	},
	{
		id: '5',
		no: 5,
		ayat: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
		latin: 'Iyyāka na‘budu wa iyyāka nasta‘īn',
		arti_id:
			'Hanya kepada Engkaulah kami menyembah dan hanya kepada Engkaulah kami mohon pertolongan.',
	},
	{
		id: '6',
		no: 6,
		ayat: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
		latin: 'Ihdinaṣ-ṣirāṭal-mustaqīm',
		arti_id: 'Tunjukilah kami jalan yang lurus,',
	},
	{
		id: '7',
		no: 7,
		ayat: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
		latin:
			'Ṣirāṭallażīna an‘amta ‘alaihim ġairil-maġḍūbi ‘alaihim wa laḍ-ḍāllīn',
		arti_id:
			'(yaitu) jalan orang-orang yang telah Engkau beri nikmat kepada mereka; bukan (jalan) mereka yang dimurkai, dan bukan (pula jalan) mereka yang sesat.',
	},
];

export const DummyJuz = [
	{
		name: 'Juz 1',
		name_start_id: 'Al-Fatihah',
		name_end_id: 'Al-Baqarah',
		name_start_arab: 'الفاتحة',
		name_end_arab: 'البقرة',
		number: '1',
		surah_id_start: '1',
		surah_id_end: '2',
		verse_start: '1',
		verse_end: '141',
	},
	{
		name: 'Juz 2',
		name_start_id: 'Al-Baqarah',
		name_end_id: 'Al-Baqarah',
		name_start_arab: 'البقرة',
		name_end_arab: 'البقرة',
		number: '2',
		surah_id_start: '2',
		surah_id_end: '2',
		verse_start: '142',
		verse_end: '252',
	},
	{
		name: 'Juz 3',
		name_start_id: 'Al-Baqarah',
		name_end_id: 'Ali Imran',
		name_start_arab: 'البقرة',
		name_end_arab: 'آل عمران',
		number: '3',
		surah_id_start: '2',
		surah_id_end: '3',
		verse_start: '253',
		verse_end: '92',
	},
	{
		name: 'Juz 4',
		name_start_id: 'Ali Imran',
		name_end_id: 'An-Nisa',
		name_start_arab: 'آل عمران',
		name_end_arab: 'النساء',
		number: '4',
		surah_id_start: '3',
		surah_id_end: '4',
		verse_start: '93',
		verse_end: '23',
	},
	{
		name: 'Juz 5',
		name_start_id: 'An-Nisa',
		name_end_id: 'An-Nisa',
		name_start_arab: 'النساء',
		name_end_arab: 'النساء',
		number: '5',
		surah_id_start: '4',
		surah_id_end: '4',
		verse_start: '24',
		verse_end: '147',
	},
	{
		name: 'Juz 6',
		name_start_id: 'An-Nisa',
		name_end_id: "Al-Ma'idah",
		name_start_arab: 'النساء',
		name_end_arab: 'المائدة',
		number: '6',
		surah_id_start: '4',
		surah_id_end: '5',
		verse_start: '148',
		verse_end: '81',
	},
	{
		name: 'Juz 7',
		name_start_id: "Al-Ma'idah",
		name_end_id: "Al-An'am",
		name_start_arab: 'المائدة',
		name_end_arab: 'الأنعام',
		number: '7',
		surah_id_start: '5',
		surah_id_end: '6',
		verse_start: '82',
		verse_end: '110',
	},
	{
		name: 'Juz 8',
		name_start_id: "Al-An'am",
		name_end_id: "Al-A'raf",
		name_start_arab: 'الأنعام',
		name_end_arab: 'الأعراف',
		number: '8',
		surah_id_start: '6',
		surah_id_end: '7',
		verse_start: '111',
		verse_end: '87',
	},
	{
		name: 'Juz 9',
		name_start_id: "Al-A'raf",
		name_end_id: "Al-A'raf",
		name_start_arab: 'الأعراف',
		name_end_arab: 'الأعراف',
		number: '9',
		surah_id_start: '7',
		surah_id_end: '7',
		verse_start: '88',
		verse_end: '206',
	},
	{
		name: 'Juz 10',
		name_start_id: 'Al-Anfal',
		name_end_id: 'At-Taubah',
		name_start_arab: 'الأنفال',
		name_end_arab: 'التوبة',
		number: '10',
		surah_id_start: '8',
		surah_id_end: '9',
		verse_start: '1',
		verse_end: '92',
	},
	{
		name: 'Juz 11',
		name_start_id: 'At-Taubah',
		name_end_id: 'Hud',
		name_start_arab: 'التوبة',
		name_end_arab: 'هود',
		number: '11',
		surah_id_start: '9',
		surah_id_end: '11',
		verse_start: '93',
		verse_end: '5',
	},
	{
		name: 'Juz 12',
		name_start_id: 'Hud',
		name_end_id: 'Yusuf',
		name_start_arab: 'هود',
		name_end_arab: 'يوسف',
		number: '12',
		surah_id_start: '11',
		surah_id_end: '12',
		verse_start: '6',
		verse_end: '52',
	},
	{
		name: 'Juz 13',
		name_start_id: 'Yusuf',
		name_end_id: 'Ibrahim',
		name_start_arab: 'يوسف',
		name_end_arab: 'إبراهيم',
		number: '13',
		surah_id_start: '12',
		surah_id_end: '14',
		verse_start: '53',
		verse_end: '52',
	},
	{
		name: 'Juz 14',
		name_start_id: 'Ibrahim',
		name_end_id: 'Al-Hijr',
		name_start_arab: 'إبراهيم',
		name_end_arab: 'الحجر',
		number: '14',
		surah_id_start: '14',
		surah_id_end: '15',
		verse_start: '53',
		verse_end: '99',
	},
	{
		name: 'Juz 15',
		name_start_id: 'An-Nahl',
		name_end_id: 'Al-Isra',
		name_start_arab: 'النحل',
		name_end_arab: 'الإسراء',
		number: '15',
		surah_id_start: '16',
		surah_id_end: '17',
		verse_start: '1',
		verse_end: '111',
	},
	{
		name: 'Juz 16',
		name_start_id: 'Al-Kahf',
		name_end_id: 'Taha',
		name_start_arab: 'الكهف',
		name_end_arab: 'طه',
		number: '16',
		surah_id_start: '18',
		surah_id_end: '20',
		verse_start: '1',
		verse_end: '135',
	},
	{
		name: 'Juz 17',
		name_start_id: 'Al-Anbiya',
		name_end_id: 'Al-Hajj',
		name_start_arab: 'الأنبياء',
		name_end_arab: 'الحج',
		number: '17',
		surah_id_start: '21',
		surah_id_end: '22',
		verse_start: '1',
		verse_end: '78',
	},
	{
		name: 'Juz 18',
		name_start_id: 'Al-Mu’minun',
		name_end_id: 'Al-Furqan',
		name_start_arab: 'المؤمنون',
		name_end_arab: 'الفرقان',
		number: '18',
		surah_id_start: '23',
		surah_id_end: '25',
		verse_start: '1',
		verse_end: '20',
	},
	{
		name: 'Juz 19',
		name_start_id: 'Ash-Shu’ara',
		name_end_id: 'An-Naml',
		name_start_arab: 'الشعراء',
		name_end_arab: 'النمل',
		number: '19',
		surah_id_start: '26',
		surah_id_end: '27',
		verse_start: '1',
		verse_end: '55',
	},
	{
		name: 'Juz 20',
		name_start_id: 'An-Naml',
		name_end_id: 'Al-Qasas',
		name_start_arab: 'النمل',
		name_end_arab: 'القصص',
		number: '20',
		surah_id_start: '27',
		surah_id_end: '28',
		verse_start: '56',
		verse_end: '88',
	},
];
