export const DummyData = [
	{
		no: 1,
		surah_idn: 'Al-Fatihah',
		surah_arabic: 'الفاتحة',
		arti: 'Pembukaan',
		total_ayah: '7',
		revealed_in: 'Mekah',
	},
	{
		no: 2,
		surah_idn: 'Al-Baqarah',
		surah_arabic: 'البقرة',
		arti: 'Sapi Betina',
		total_ayah: '286',
		revealed_in: 'Madinah',
	},
	{
		no: 3,
		surah_idn: "Ali 'Imran",
		surah_arabic: 'آل عمران',
		arti: 'Keluarga Imran',
		total_ayah: '200',
		revealed_in: 'Madinah',
	},
	{
		no: 4,
		surah_idn: "An-Nisa'",
		surah_arabic: 'النساء',
		arti: 'Wanita',
		total_ayah: '176',
		revealed_in: 'Madinah',
	},
	{
		no: 5,
		surah_idn: "Al-Ma'idah",
		surah_arabic: 'المائدة',
		arti: 'Hidangan',
		total_ayah: '120',
		revealed_in: 'Madinah',
	},
	{
		no: 6,
		surah_idn: "Al-An'am",
		surah_arabic: 'الأنعام',
		arti: 'Binatang Ternak',
		total_ayah: '165',
		revealed_in: 'Mekah',
	},
	{
		no: 7,
		surah_idn: "Al-A'raf",
		surah_arabic: 'الأعراف',
		arti: 'Tempat Tertinggi',
		total_ayah: '206',
		revealed_in: 'Mekah',
	},
	{
		no: 8,
		surah_idn: 'Al-Anfal',
		surah_arabic: 'الأنفال',
		arti: 'Harta Rampasan Perang',
		total_ayah: '75',
		revealed_in: 'Madinah',
	},
	{
		no: 9,
		surah_idn: 'At-Tawbah',
		surah_arabic: 'التوبة',
		arti: 'Pengampunan',
		total_ayah: '129',
		revealed_in: 'Madinah',
	},
	{
		no: 10,
		surah_idn: 'Yunus',
		surah_arabic: 'يونس',
		arti: 'Nabi Yunus',
		total_ayah: '109',
		revealed_in: 'Mekah',
	},
	{
		no: 11,
		surah_idn: 'Hud',
		surah_arabic: 'هود',
		arti: 'Nabi Hud',
		total_ayah: '123',
		revealed_in: 'Mekah',
	},
	{
		no: 12,
		surah_idn: 'Yusuf',
		surah_arabic: 'يوسف',
		arti: 'Nabi Yusuf',
		total_ayah: '111',
		revealed_in: 'Mekah',
	},
];
